config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sessions/new'
	get '/login/:user_id' => 'sessions#login_local' if Rails.env.development?
  get '/users/:id/creation_form' => 'users#creation_form'
  get '/users/auth/:provider/callback', to: 'sessions#create'
  resources :event_tags
  resources :interests
  resources :events
  resources :users, :except => :index
  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/', to: 'events#home'
  get '/events/new', to: 'events#new'
  get '/events/new/trumba', to: 'events#new_trumba'
  get 'sponsor/:sponsor', to: 'events#filter_events'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search', to: 'events#search', as: 'search'
  get '/filter_events', to: 'events#filter_events', as: 'filter_events'
  post '/get_events', to: 'users#get_events', as: 'get_events'
  post '/change_privacy', to: 'users#change_privacy', as: 'change_privacy'
  get 'users/:id/new_account', to: 'users#creation_form', as: 'new_account'
  get '/top_events_json', to: 'events#top_events', :defaults => { :format => :json }
  get '/top_events_on_day/:date', to: 'events#top_events_on_day', :defaults => { :format => :json }


  get 'users/:calendar_hash/calendar-sync', to: 'users#to_icalendar'

  get '/events/:id/checkin', to: 'events#checkin'


  match '/404', :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  post '/rsvp', to: 'rsvps#rsvp', as: 'rsvp'
  post '/add_interest', to: 'interests#add_interest', as: 'add_interest'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#home'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events
	has_many :rsvps
	has_many :events, through: :rsvps
	has_many :interests
	has_many :tags, through: :interests
	devise :omniauthable, omniauth_providers: [:saml]

	validates :phone, :allow_blank => true, format: { with:  /\d[0-9]\)*\z/, message: "bad format" }, :numericality => true, length: {minimum: 10, maximum: 10}

	class << self
		def from_saml(auth_hash)
			puts "auth_hash = #{auth_hash}"
			@data = auth_hash['extra']['raw_info'].attributes
			puts "@data = #{@data}"
			uid = parse('urn:oid:0.9.2342.19200300.100.1.1')
			user = where(uid: uid, provider: auth_hash['provider']).first_or_initialize
			@new_record = user.new_record?
			user.first_name = parse('urn:oid:2.5.4.42')
			user.last_name = parse('urn:oid:2.5.4.4')
			user.email = parse('urn:oid:0.9.2342.19200300.100.1.3')
			user.bio = 'No bio yet...'
			user.calendar_hash = User.digest("#{user.uid}#{user.provider}").gsub!(/[^0-9A-Za-z]/, '') if @new_record
			user.save!
			user
		end

		def parse key
			@data[key][0]
		end

	end

	def name
		"#{first_name} #{last_name}"
	end

	def email
		return "#{uid}@brandeis.edu"
	end

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

end

app/controllers/users_controller.rb
require 'icalendar'

class UsersController < ApplicationController
  before_action :logged_in?
	skip_before_action :verify_authenticity_token

  before_action :set_rsvps, only: [:show, :get_events]

  def get_events
    @active_tab = params[:index].to_i
    respond_to do |format|
      format.js
    end
  end

  def change_privacy
    @user = User.find(params[:user_id])
    @user.hide_rsvp = !@user.hide_rsvp
    @user.save
    respond_to do |format|
        format.js
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path if @user != current_user
  end

  def creation_form
    @user = User.find(params[:id])
    redirect_to root_path if @user != current_user
  end

  def to_icalendar
    @user = User.find_by(calendar_hash: params[:calendar_hash])
    respond_to do |format|
      format.html
      format.ics do
        headers['Content-Type'] = "text/calendar; charset=UTF-8"
        cal = Icalendar::Calendar.new
        @user.events.each do |e|
          event = Icalendar::Event.new
          event.dtstart = e.start
          event.dtend = e.end
          event.summary = e.name
          event.uid = event.url = e.url
          event.location = e.location
          event.description = e.description_text.html_safe
          cal.add_event(event)
        end
        cal.publish
        render text: cal.to_ical
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
    authorize! :new, @user
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
		respond_to do |format|
			format.html
			format.js
		end
  end

  # POST /users
  # POST /users.json
  def create
		user_params["phone"] = user_params["phone"].gsub!(/[^0-9A-Za-z]/, '') if user_params["phone"]
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_account_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    authorize! :update, @user
		user_params["phone"] = user_params["phone"].gsub!(/[^0-9A-Za-z]/, '') if user_params["phone"]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html
        format.json { render json: @user.errors, status: :unprocessable_entity }
				format.js
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    authorize! :destroy, @user
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :bio, :is_host, :phone, :street, :city, :zip_code, :state, :text_time_num, :text_time_unit, :email_time_num, :email_time_unit)
  end
end

app/helpers/users_helper.rb
module UsersHelper

    def get_events_helper
        @user_events = case @active_tab
        when 0
            map_to_events current_user.rsvps.select {|r| r.choice == 1 && !r.event.start.past?}
        when 1
            map_to_events current_user.rsvps.select {|r| r.choice == 2 && !r.event.start.past?}
        when 2
            map_to_events current_user.rsvps.select { |r| r.event.start.past? }
        end

        if @user_events.nil?
            @user_events = []
        end

        @user_events = @user_events.sort_by { |e| e.start  }.paginate(page: params[:page], per_page: 8)
    end

    def map_to_events rsvps
        rsvps.map { |r| r.event }
    end

    def opt_in_or_out(user)
        "Click here to #{privacy_variable(user)} events' RSVP lists!"
    end

    def privacy_statement(user)
        user.hide_rsvp ? 'Your RSVPs to events are currently anonymous!' : 'Your name is currently being shown on events you\'ve RSVP\'d to!'
    end

    def privacy_variable(user)
        user.hide_rsvp == true ? 'SHOW your name on' : 'HIDE your name from'
    end

    def privacy_button_color(user)
      user.hide_rsvp == true ? 'btn btn-primary' : 'btn btn-danger'
    end

    # def set_active
    #     @active = 0 if @active.nil?
	# 	@tab_classes = []
	# 	@tab_pane_classes = []
	# 	for i in 0..2
	# 		unless i == @active
	# 			@tab_classes[i] = ''
	# 			@tab_pane_classes[i] = 'tab-pane fade'
	# 		end
	# 	end
	# 	@tab_classes[@active] = 'class = active'
	# 	@tab_pane_classes[@active] = 'tab-pane fade in active'
	# end

end

app/views/users/_account.html.erb
<h1 class="section-titles text-center">Settings</h1>

<div class="container" id="userdashboard">

	<div class="row" id="tags-section-user">
		<div class="col-md-12 text-left">
			<h4>Your Event Interests:</h4>
			<% Tag.all.sort_by { |t| t.name }.each do |tag| %>
			<%= render partial: 'interests/interest_button', locals: {tag: tag} %>
			<% end %>
		</div>

	</div>

	<%= form_for current_user, remote: true do |f| %>
	<% if current_user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(current_user.errors.count, "error") %>
			prohibited this @user from being saved:</h2>

		<ul>
			<% current_user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<h3>Reminder Settings</h3>
	<div class="row form-group" id="hidden_fields">
		<div class="col-md-4">
			<%= f.label :Phone_Number, "Want to receive SMS alerts about events? Please enter your mobile phone number:" %>
			<br/><br/>
			<%= f.text_field :phone, class: "form-control" %>
		</div>
		<div class="col-md-4 form-inline">
			<%= f.label :Email_alert_time, "How far in advance do you want to receive text reminders? (Leave 0 for never)" %>
			<br/><br/>
			<%= f.number_field :text_time_num, class: "form-control" %>
			<%= f.select :text_time_unit, ['days', 'hours', 'minutes'], { :include_blank => "Please select a time"}, {:class => "form-control"}%>
		</div>
		<div class="col-md-4 form-inline">
			<%= f.label :Email_alert_time, "How far in advance do you want to receive email reminders at #{current_user.email}? (Leave 0 for never)" %>
			<br/><br/>
			<%= f.number_field :email_time_num, class: "form-control" %>
			<%= f.select :email_time_unit, ['days', 'hours', 'minutes'], { :include_blank => "Please select a time"}, {:class => "form-control"}%>
		</div>
	</div>
	<div class="actions">
		<%= f.submit "Update reminder settings", class: "btn btn-default btn-transparent"%>
	</div>

	<% end %>

	<div class="row">

		<div class="col-md-6">
			<h3>Subscribe to Calendar Feed</h3>
			<p>Subscribe to your own personal calendar, filled with the events you've RSVP'd to!
				<br/>
				Just press one of the below buttons or manually subscribe with this link:
				<br/>
				<span style="word-wrap: break-word;"><%="webcal://deistoday.com/users/#{current_user.calendar_hash}/calendar-sync"%></span></p>
			<%= link_to("Subscribe to Calendar Feed", "webcal://deistoday.com/users/#{current_user.calendar_hash}/calendar-sync", :class=>"btn btn-default btn-transparent", :id =>"calendar-feed-button" ) %>
			|
			<%= link_to("Add to Google Calendar", "https://calendar.google.com/calendar/render?cid=webcal://deistoday.com/users/#{current_user.calendar_hash}/calendar-sync.ics#main_7", :class=>"btn btn-default btn-transparent", :target=>:blank, :id =>"calendar-feed-button" ) %>
		</div>
	<div class="col-md-6 form-inline">
		<div id="privacy">
			<%= render partial: 'change_privacy', locals: {user: User.find(current_user.id)} %>
		</div>
	</div>

	</div>

</div>

</div>

<div class="col-md-12">
<br/>
</div>

</div>

<script type="text/javascript">
//Phone appears if checkbox is cliked or not. This is for if a user unselects adding a phone number it will delte it from the field.
$(function () {

	// Get the form fields and hidden div
	var checkbox = $("#trigger");
	var hidden = $("#hidden_fields");

	// Hide the fields. hidden.hide();
	checkbox.change(function () {
		// Check to see if the checkbox is checked. If it is, show the fields and populate the input. If not, hide the fields.
		if (checkbox.is(':checked')) {
			// Show the hidden fields.
			hidden.show();
		} else {
			// Make sure that the hidden fields are indeed hidden.
			hidden.hide();
			//if hidden then erases value
			$("#hidden_field").val("");
		}
	});
});
</script>

app/views/users/_change_privacy.html.erb
<h3>Privacy</h3>
<h4><%= privacy_statement(user) %></h4>
<%= button_to opt_in_or_out(user), change_privacy_path(user_id: user.id), class: privacy_button_color(user), :remote => true %>

app/views/users/change_privacy.js.erb
$("#privacy").html("<%=escape_javascript(render(:partial => 'change_privacy', locals: {user: @user}))%>")

app/views/users/creation_form.html.erb
<h2 class="section-titles text-center"><%= "Welcome, #{current_user.name}"%></h2>
<div class="container">
	<div class="row">
	   <%= render partial: 'account' %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: 'users/account' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" >
    <% provide(:title, @user.first_name) %>

    <div class="top-thumbnail profile-banner text-center">
        <%= image_tag "your-profile.png", class:"img-responsive" %>
        <div class="top-caption">
            <h1>
                <%= @user.first_name %>'s Events
            </h1>

        </div>
    </div>

    <% @active_tab = 0 %>
    <%= render partial: 'events/user_events' %>

</div>

app/views/users/update.js.erb
alert("<%=@user.errors.full_messages.to_sentence%>");