config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sessions/new'
	get '/login/:user_id' => 'sessions#login_local' if Rails.env.development?
  get '/users/:id/creation_form' => 'users#creation_form'
  get '/users/auth/:provider/callback', to: 'sessions#create'
  resources :event_tags
  resources :interests
  resources :events
  resources :users, :except => :index
  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/', to: 'events#home'
  get '/events/new', to: 'events#new'
  get '/events/new/trumba', to: 'events#new_trumba'
  get 'sponsor/:sponsor', to: 'events#filter_events'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search', to: 'events#search', as: 'search'
  get '/filter_events', to: 'events#filter_events', as: 'filter_events'
  post '/get_events', to: 'users#get_events', as: 'get_events'
  post '/change_privacy', to: 'users#change_privacy', as: 'change_privacy'
  get 'users/:id/new_account', to: 'users#creation_form', as: 'new_account'
  get '/top_events_json', to: 'events#top_events', :defaults => { :format => :json }
  get '/top_events_on_day/:date', to: 'events#top_events_on_day', :defaults => { :format => :json }


  get 'users/:calendar_hash/calendar-sync', to: 'users#to_icalendar'

  get '/events/:id/checkin', to: 'events#checkin'


  match '/404', :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  post '/rsvp', to: 'rsvps#rsvp', as: 'rsvp'
  post '/add_interest', to: 'interests#add_interest', as: 'add_interest'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#home'
end

app/models/event.rb
require 'time'
class Event < ApplicationRecord
	belongs_to :user
	alias_attribute :host, :user
	has_many :rsvps
	has_many :users, through: :rsvps
	has_many :event_tags
	has_many :tags, through: :event_tags

	validates :name, presence: true, allow_blank: false, length: { maximum: 50, minimum: 1 }
	validates :description, presence: true, allow_blank: false, length: { minimum: 80 }
	validates :location, presence: true
	validates :start, presence: true
	validates :trumba_id, uniqueness: true


	def host
		user
	end

	def url
		"deistoday.com/events/#{self.id}"
	end

	has_attached_file :event_image, styles: {
		thumb: '100x100>',
		square: '200x200#',
		medium: '300x300>',
		large: '750x240#'
	}

	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :event_image, content_type: /\Aimage\/.*\Z/

	def self.search(params)
		if params
			events = Event.all
			#name or description
			n_or_d = params[:event]
			location = params[:location]
			date = params[:date] || Time.now
			date = Date.strptime(params[:date].to_s, "%m/%d/%Y")
			events = events.where(['start > ? AND end < ?'], "%#{date}%", "%#{date.end_of_day}%")
			events = events.where(['lower(name) LIKE ? OR lower(description) LIKE ?', "%#{n_or_d.downcase}%", "%#{n_or_d.downcase}%"]) if n_or_d.present?
			events = events.where(['lower(location) LIKE ?',"%#{location.downcase}%"]) if location.present? && location != "all"
			events = events.where(:start => date.beginning_of_day..date.end_of_day) if date.present?

			return events

		else
			Event.where('start > ?', Time.now).order('id ASC')
		end
	end

end

app/controllers/events_controller.rb
require 'active_support/core_ext'

class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :set_rsvps, only: [:index, :show, :search, :filter_events]

	def search
		@events = Event.search(params).paginate(page: params[:page], per_page: 12)
		@locations = Location.all.select{|l| !l.event_count.nil? && (l.event_count > 0)}
		respond_to do |format|
			format.html
			format.js
		end
	end

	# Get events based on search parameters
	def index
		@events = Event.all.to_ary.select { |e| e.start > Time.now }
		@events = @events.sort_by { |e| e.start }.paginate(page: params[:page], per_page: 12)
		@locations = Location.all.select{|l| !l.event_count.nil? && (l.event_count > 0)}
	end

	def filter_events
		@locations = Location.all.select{|l| !l.event_count.nil? && (l.event_count > 0)}
		@events = []
		if(params[:my_interests])
			@events = Set.new
			@current_user.tags.each { |t| @events.merge t.events }
			@events = @events.select { |e| e.start > Time.now}
		elsif params[:location]
			@events = Location.find_by(name: params[:location]).events.where('start > ?', Time.now)
		elsif params[:date]
			@events = filter_dates(params[:date])
		elsif params[:tag]
			@events = filter_tags(params[:tag])
		elsif params[:sponsor]
			search_phrase = search_by_sponsor(params[:sponsor].downcase)
			@events = Event.where("sponsor like ?", "%" + search_phrase + "%")
			@events = @events.where('start > ?', Time.now)


		else
			@events = Event.where('start > ?', Time.now)
		end
		@events = @events.sort_by { |e| e.start }.paginate(page: params[:page], per_page: 12)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def home
		if request.remote_ip.include?("129.64") || request.remote_ip.include?("127.0.0.1")
			redirect_to events_path
		else
		redirect_to events_path if logged_in?
		all_events = Event.where("start > ?", Time.now)
		@items = all_events.pluck(:name)
		@top_events = all_events.sort_by(&:rsvps_count).last(4).reverse
		@locations = Location.all.pluck(:name) # grab_locations
		@top_tags = Tag.all.sort_by(&:events_count).last(7).reverse.map { |t| [t.events.count, t.name, t.id, t.image] }
	end
end

	def show
		@tags = EventTag.where(event_id: @event.id)
		if !@lat_lng.nil?
			coordinates = @lat_lng.split('_')
			@current_latitude = coordinates[0]
			@current_longitude = coordinates[1]
		else
			# For local use, we hardcoded a test coordinate pair
			@current_latitude = 42.366365
			@current_longitude = -71.259591
		end
		@location = geolocation
		geo_localization = "#{@current_latitude},#{@current_longitude}"
		#@current_address = Geocoder.search(geo_localization).first.address || "Brandeis University, Waltham, MA, 02453"
		@address = "#{@event.location}, Waltham, MA, 02453"
	end

	def top_events
		@top_events = Event.all.sort_by(&:rsvps_count).last(10).reverse.map { |e| [e.name, e.start, e.location] }

		respond_to do |format|
			format.html {}
			format.json do
				render json: @top_events.to_json
			end
		end
	end

	def top_events_on_day
		# for alexa and other chat bots as well as future integration with other apps
		date = params[:date].to_date.strftime('%m-%d-%Y').to_date
		@top_events = Event.where(start: date.beginning_of_day..date.end_of_day) if date.present?
		respond_to do |format|
			format.html {}
			format.json do
				render json: @top_events.to_json
			end
		end
	end

	# GET /events/new
	def new
		@event = Event.new
		authorize! :new, @event
	end

	def checkin
		# respond_to do |format|
		# 	format.html {}
		# end
	end


	# GET /events/1/edit
	def edit
		authorize! :edit, @event
	end


	# POST /events
	# POST /events.json
	def create
		@event = Event.new(event_params)
		@event.host = current_user
		authorize! :create, @event
		respond_to do |format|
			if @event.save
				format.html { redirect_to @event, notice: 'Event was successfully created.' }
				format.json { render :show, status: :created, location: @event }
			else
				format.html { render :new }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /events/1
	# PATCH/PUT /events/1.json
	def update
		authorize! :update, @event
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to @event, notice: 'Event was successfully updated.' }
				format.json { render :show, status: :ok, location: @event }
			else
				format.html { render :edit }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event.destroy
		authorize! :destroy, @event
		respond_to do |format|
			format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_event
		@event = Event.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def event_params
		params.require(:event).permit(:name, :description, :location, :start, :end, :price, :host_id, :event_image, :date, :tag, :sponsor)
	end

	def geolocation
		loc = []
		loc = Geocoder.coordinates("#{@event.location}, Brandeis University, Waltham, MA, 02453")
		loc = Geocoder.coordinates('Brandeis University, Waltham, MA, 02453') if loc.nil?
		loc
	end

	def filter_tags(tag)
		Tag.find(tag).events.where('start > ?', Time.now)
	end

	def filter_dates(filter)
		if filter == 'today'
			Event.where(start: Time.now..Date.today.end_of_day)
		elsif filter == 'tomorrow'
			Event.where(start: Date.tomorrow.beginning_of_day..Date.tomorrow.end_of_day)
		elsif filter == 'this week'
			Event.where(start: Time.now.beginning_of_day..Date.today.next_day(7).end_of_day)
		elsif filter == 'next week'
			Event.where(start: Date.today.next_day(7).beginning_of_day..Date.today.next_day(14).end_of_day)
		elsif filter == 'this weekend'
			Event.where(start: Date.today.beginning_of_day..Date.today.next_day(7).end_of_day).select { |e| e.start.to_date.on_weekend? }
		else
			Event.where('start < ?', Time.now).reverse
		end
	end

	def search_by_sponsor(search_phrase)
		if search_phrase.include?("-")
			search_phrase = search_phrase.gsub("-", " ")
		end
	  return search_phrase
    end
end

app/helpers/events_helper.rb
require 'nokogiri'

module EventsHelper
	def top_image_text
		s = ''
		if params[:my_interests]
			s << '<h1 style="color:#fff;">Events For Your Interests</h1><h2>'
			current_user.tags.pluck(:name).sort.each { |t| s << "#{t} | "}
			s = s[0...-2]
			s << '</h2>'
		else
			s << '<h1>'
			s <<
			if params[:date] && params[:date] != ''
			params[:date].titleize.to_s
			elsif params[:tag]
			"Category: #{Tag.find(params[:tag]).name.titleize}"
			elsif params[:location] && params[:location] != 'all'
			params[:location].titleize.to_s
			elsif params[:sponsor]
			"Events by " + params[:sponsor].split.map(&:capitalize)*' '
			else
			'All Events'
			end
			s << '</h1>'
		end
		s.html_safe
	end

	def rsvps_to_show(event)
		event.users.where(hide_rsvp: false).map { |u| u.name }.sort
	end

	def anonymous_rsvps(event, to_show)
		event.rsvps.count - to_show.count
	end

	def list_event_helper(event, col_length)
		string = ''
		string << "<div class='#{col_length} portfolio-item'>"
		string << event_image(event)
		string << "<h4> <a href='#{event_path(event.id)}'> #{(truncate event.name, length: 50, :escape => false)}</a></h4>"
		string << list_tags(event)
		string << "<p class='event-description-home'>#{(truncate event.description_text, length: 65, :escape => false)}</p>"
		string << time(event) + location(event)
		string.html_safe
	end

	def list_tags(e)
		string = "<div class='text-left event-tags'>"
		icon = "<span class='glyphicon glyphicon-tags' class='col-md-2'></span>"
		string << "<p>#{icon} #{e.top_tags}  </p>"
		string << '</div>'
	end

	def event_image(event)
		s = ''
		s << "<a href='#{event_path(event.id)}'>"
		if event.event_image_file_name.nil?
			if event.image_id.blank?
				s << image_tag('missing_thumbnail.png').html_safe
			else
				s << image_tag(event.image_id).html_safe
			end
		else
			s << image_tag(event.event_image(:square)).html_safe
		end
		s << '</a>'
	end

	def time(event)
		start_str = event.start.strftime('%-m/%-d %l:%M %p')
		end_str = event.start.to_date == event.end.to_date ? event.end.strftime('%l:%M %p') : event.end.strftime('%-m/%-d %l:%M %p')
		<<-eos
		<div class="row">
		<div class="col-xs-12">
		<span class="glyphicon glyphicon-time" id="icon-home" class="col-md-4"></span>
		#{start_str} - #{end_str}
		</div>
		eos
	end

	def location(event)
		string = "<div class='col-xs-12'>"
		string << "<span style='margin-left: -21px;' class='glyphicon glyphicon-map-marker' id='icon-location'></span>"
		to_truncate = event.location
		trunc = to_truncate.gsub(/[^0-9A-Za-z]|Room.*/, ' ').split.first(2).join(' ')
		string << " " + trunc.to_s
		string << '</div>'
		string << '</div>'
	end

	def sidebar(locations)
		string = ''
		string << "<button type='button' class='btn btn-link' data-toggle='collapse' data-target='#locations'><h4><strong>Locations</strong></h4></button>"
		string << "<div class='collapse' id='locations'>"
		string << '<p>' + link_to('All Locations', filter_events_path, remote: true) + '</p>'

		locations.sort.each do |l|
			count = l.event_count.to_s
			s = l.name + ' (' + count + ')'
			string << '<p>' + link_to(s, filter_events_path(location: l.name), remote: true) + '</p>'
		end

		string << '</div>'
		string << '<hr>'
		string.html_safe
	end

	def sidebar_tags
		string = ''
		string << "<button type='button' class='btn btn-link' data-toggle='collapse' data-target='#tags'><h4><strong>Categories</strong></h4></button>"
		string << "<div class='collapse' id='tags'>"
		string << '<p>' + link_to('All Categories', filter_events_path, remote: true) + '</p>'
		Tag.all.sort.each do |tag|
			if tag.event_count > 0
			  s = ' (' + tag.event_count.to_s + ')'
			  string << '<p>' + link_to(tag.name + s, filter_events_path(tag: tag.id), remote: true) + '</p>'
		    end
		end

		string << '</div>'
		string << '<hr>'
		string.html_safe
	end

	def sidebar_date
		string = ''
		string << "<button type='button' class='btn btn-link' data-toggle='collapse' data-target='#dates'><h4><strong>Dates</strong></h4></button>"
		string << "<div class='collapse' id='dates'>"
		string << '<p>' + link_to('All Dates', filter_events_path, remote: true) + '</p>'
		string << '<p>' + link_to('Today', filter_events_path(date: 'today'), remote: true) + '</p>'
		string << '<p>' + link_to('Tomorrow', filter_events_path(date: 'tomorrow'), remote: true) + '</p>'
		string << '<p>' + link_to('This Week', filter_events_path(date: 'this week'), remote: true) + '</p>'
		string << '<p>' + link_to('This Weekend', filter_events_path(date: 'this weekend'), remote: true) + '</p>'
		string << '<p>' + link_to('Next Week', filter_events_path(date: 'next week'), remote: true) + '</p>'
		string << '<p>' + link_to('This Month', filter_events_path(date: 'this month'), remote: true) + '</p>'
		string << '<p>' + link_to('Past Events', filter_events_path(date: 'past events'), remote: true) + '</p>'
		string << '</div>'
		string << '<hr>'
		string.html_safe
	end

	def sidebar_my_interests
		interest_events = Set.new
		current_user.tags.each { |t| interest_events.merge t.events }
		count = interest_events.count
		string = ''
		string << "<button type='button' class='btn btn-link'> <h4><strong>"
		string << link_to("My Interests (#{count})", filter_events_path(my_interests: true), remote: true)
		string << "</strong></h4></button>"
		string.html_safe
	end

	def is_host
		current_user && @event.host == current_user
	end

	# def time_to_destination(starting, destination, type)
	# 	s = ''
	# 	drive_time_in_minutes = GoogleDirections.new(starting, destination, type).drive_time_in_minutes
	# 	hours = drive_time_in_minutes / 60
	# 	minutes = drive_time_in_minutes % 60
	# 	s = hours.to_s + ' hours ' + minutes.to_s + ' minutes'
  #
	# 	s.html_safe
	# end

	def next_min_trumba
		"Your next manual event should have Trumba ID: #{Event.pluck(:trumba_id).min - 1}"
	end
end

app/views/events/_display_events.html.erb
<section class="events_all_section">
	<div class="container">
		<div class="top-thumbnail text-center">
			<%= image_tag "All-Event.png", class:"img-responsive" %>
			<div class="top-caption" id = "top-image">
				<%= render partial: 'top_caption' %>
			</div>
		</div>



		<div class="row">
			<div class=" events_list">
				<div class="col-md-2 left-side-column">
					<%= sidebar_date %>
					<%= sidebar_tags %>
					<%= sidebar(@locations) %>
					<%= sidebar_my_interests if logged_in? %>
					<hr>

				</div>
			</div>
			<div class="col-md-10">
	 <div class = "form-group">

	 <%= form_tag(search_path, :method => "get", remote: true) do %>
	 <%= text_field_tag :event, params[:event], placeholder: "Search here for anything", class: "form-control" %>
	 <%= submit_tag 'Search', :class => 'btn btn-default hidden' %>
	 <% end %>
			<div id="events-happening">
				<%= render partial: 'events/events_exist' %>
			</div>
			<div id="paginate">
				<%= render partial: 'events/paginate' %>
			</div>

			</div>

		</section <!-- /.row --> <p id="notice"><%= notice %></p>

app/views/events/_event_section.html.erb
<div id="event_section">
	<div class="col-md-12 RSVP_section">
		<h3 class="section-titles text-center"><%= section_titles[active_tab] %></h3>
		<% get_events_helper %>

		<% if @user_events.length != 0%>

		<% @user_events.each do |e| %>

		<%= render partial: 'events/list_event', locals: {event: e, col_length: "col-md-3"} %>
		<% end %>

		<% else %>
		<p>You don't have any events. Add some!</p>
		<% end %>

	</div>

</div>

app/views/events/_event_section_with_recs.html.erb
<div id="event_section">
	<div class="col-md-12 RSVP_section">
		<h3 class="section-titles text-center"><%= section_titles[active_tab] %></h3>
		<% if active_tab != 4 %>
		<% get_events_helper %>
		<% if @user_events.length != 0%>

		<% @user_events.each do |e| %>

		<%= render partial: 'events/list_event', locals: {event: e, col_length: "col-md-3"} %>
		<% end %>

		<% else %>
		<p>You don't have any events. Add some!</p>
		<% end %>

		<% else %>

		<%= render partial: 'users/account' %>

		<% end %>

	</div>

</div>

app/views/events/_event_tabs.html.erb
<% for index in 0..2 %>
  <!-- <div class="col-sm-offset-2"> -->
<div class="user_tab_<%= @active_tab == index %> col-md-4 text-center user_tab">
<%= button_to tab_titles[index], get_events_path(index: index), :remote => true, class: 'btn btn-default user_tab_button'  %>
<!-- </div> -->
</div>

<% end %>

app/views/events/_event_tabs_with_recs.html.erb
<% for index in 0..4 %>
  <!-- <div class="col-sm-offset-2"> -->
<div class="user_tab_<%= @active_tab == index %> col-md-3 text-center user_tab">
<%= button_to tab_titles[index], get_events_path(index: index), :remote => true, class: 'btn btn-default user_tab_button'  %>
<!-- </div> -->
</div>

<% end %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
<% if event.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(event.errors.count, "error") %>
		prohibited this event from being saved:</h2>
	<ul>
		<% event.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<label for="formGroupExampleInput">Event Name</label>
			<%= f.text_field :name, placeholder: "Enter Event Name", class: "form-control"%>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label for="formGroupExampleInput">Event Location</label>
			<%= f.collection_select :location, Location.order(:name),:name,:name, {:include_blank => "Please select a location"}, {:class=>"form-control"}  %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="form-group">
			<label for="formGroupExampleInput">Event Description, 80 Character min</label>
			<%= f.text_area  :description, placeholder: "Event Description, 80 Character min", class: "form-control"%>
		</div>
	</div>
</div>
<!-- <div class="form-group">
	<label for="formGroupExampleInput">Event Location</label>
	<%= f.text_field :location, placeholder: "Enter Event Name", class: "form-control"%>
</div> -->
<div class="row">
	<div class="field col-md-6">
		<%= f.label :start %>
		<br/>
		<%= f.datetime_select :start, class: "form-control" %>
	</div>

	<div class="field col-md-6">
		<%= f.label :end %>
		<br/>
		<%= f.datetime_select :end, class: "form-control" %>
	</div>
	<!-- end row -->
</div>

<div class="row">
	<div class="field col-md-6">
		<%= f.label :price %>
		<div class="input-group">
			<span class="input-group-addon">$</span>
			<%= f.number_field :price %>
		</div>
	</div>
	<div class="field col-md-6">
		<%= f.label :event_image %>
		<%= f.file_field :event_image %>
	</div>
</div>

<!-- user selects tags for events -->
<div class="row">
	<div class="col-md-12 tags field">
		<%= f.label "Tags" %>
		<br/>
		<% Tag.all.each do |tags| %>
		<div class="col-md-3">
			<%= check_box_tag "event[tag][]", tags.id, @event.tags.include?(tags.id) %>
			<%=tags.name %>
			<br/>
		</div>
		<%end %>
	</div>
</div>

<div class="actions field">
	<%= f.submit class: "btn btn-default btn-transparent" %>
</div>

<% end %>

<style>
	.field {
		padding-top: 10px;
	}

</style>

app/views/events/_list_event.html.erb
<%= list_event_helper(event, col_length)%>

<%= render partial: 'events/rsvp_button', locals: {event: event} unless @current_user.nil? %>

</div>

app/views/events/_search.html.erb
<div class="search hidden-phone hidden-md hidden-sm hidden-xs">
	<form id="search" role="form" action=<%=search_path%> method="get">
		<div class="col-md-4">
			<div class="form-group">

				<input type="text" class="form-control" id="search-complete" placeholder="Search Events by Name or Description" name="event">
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group">
				<select class="form-control" name="location" id="location" form="search">
						<option value="all">All Locations</option>
					<%@locations.sort.each do |l|%>
						<option value=<%=l%>><%=l%></option>
					<%end%>
				</select>
				<!-- <label class="sr-only" for="location">Location</label>
				<input type="text" class="form-control" id="location" placeholder="Location" name="location"> -->
			</div>
		</div>
		<div class="col-md-2">
			<div class="form-group">
				<div id='datetimepicker1' class="input-group">
					<input type="date" class="form-control" placeholder="MM/DD/YYYY" name=date>
					<span class="input-group-addon">
						<i class="glyphicon glyphicon-calendar"></i>
					</span>
				</div>
			</div>
		</div>
		<div class="col-md-2 form-group">
			<button type="submit" class="btn btn-default btn-white">Search</button>
		</div>
	</form>
</div>

app/views/events/_top_caption.html.erb
<h1><%= top_image_text %></h1>

app/views/events/filter_events.js.erb
$("#top-image").html("<%=escape_javascript(render(:partial => 'top_caption'))%>")
$("#events-happening").html("<%=escape_javascript(render(:partial => 'events_exist'))%>")
$("#paginate").html("<%=escape_javascript(render(:partial => 'paginate'))%>")

app/views/events/show.html.erb
<div class="container">
	<div class="row">
		<% if @event.start < Time.now %>
		<div class="alert alert-warning">
			<strong>This event has already taken place!</strong>
			Please view upcoming events
			<%= link_to "Here", events_path %>
		</div>
		<% end %>

		<div class="col-md-8">
			<div class="top-image">
				<% if @event.event_image_file_name.nil? %>
				<% if @event.image_id.blank? %>
				<%= image_tag "missing_large.png", class: "event-top-image" %>
				<%else %>
				<%= image_tag "#{@event.image_id}", class: "event-top-image" %>
				<% end %>
			<% else %>
				<%= image_tag @event.event_image(:large), class: "event-top-image"%>
				<% end %>
			</div>
		</div>
		<div class="col-md-4">
			<h2><%= @event.name.html_safe%></h2>


			<% if logged_in? %>
			<div class="center-block">
				<div class="btn-group pull-left rsvp-button-group" role="group" aria-label="...">
					<%= render partial: 'rsvp_button', locals: {event: @event} %>
				</div>
			</div>

			<%else%>
			<div class="center-block" role="group" aria-label="...">
					<div class="btn-group pull-left rsvp-button-group" role="group" aria-label="...">
						<p>
							<%=button_to "Login", user_saml_omniauth_authorize_path, class: rsvp_button_color%>
							to RSVP to this event!
						</p>
				</div>
			</div>
			<%end%>
		</div>
	</div>

	<div class="row main_body">
		<div class="col-md-2 individual_event_sidebar">

			<%= sidebar_individual_event %>
			<%if logged_in?%>
			<button class="btn btn-default btn-inverse " data-toggle="modal" data-target="#myModal">RSVP List </button>
			<%end%>
			<%= social_share_button_tag(@event.name, :url =>"https://www.deistoday.com/events/#{@event.id}") %>
			</div>
		<div class="col-md-10 event-description">
			<% if !@event.description.nil? %>
			<%= @event.description.html_safe %>
		<% else %>
			<%= "This event has no description." %>
			<% end %>

			<div class=" tags-section">

				<!-- <h4>Tags</h4> -->
				<% @event.tags.each do |tag| %>
				<%= link_to tag.name, events_path(:tag => tag.id), class: "btn btn-default btn-inverse btn-tags" , :method => :get%>

				<% end %>
			</div>
				<div id="map" style='width: 100%; height: 250px;'></div>
		</div>


		<div id="rsvp_list">
				 <%= render "events/display_rsvps",  locals: {event: @event} %>
		 </div>
		<!-- <div class="container">
		</div>
			<div class="row">
				<div class="col-md-12">
				<% unless @location.nil?%>
					<div id="map" style='width: 100%; height: 220px;'></div>
				<%end%>
				</div>
		</div>
</div> -->
	</div>

	<% if is_host %>
	<%= link_to 'Edit', edit_event_path(@event) %>
	|
	<%= link_to 'Back', events_path %>
	<% end %>

</div>

<% if !@current_latitude.nil? && !@location.nil?%>
<script type="text/javascript">

	var handler = Gmaps.build('Google');
	handler.buildMap({
		internal: {
			id: 'map'
		},
		zoom: 13
	}, function () {

		var directionsService = new google.maps.DirectionsService();
		var directionsDisplay = new google.maps.DirectionsRenderer();

		directionsDisplay.setMap(handler.getMap());
		var request = {
			origin: new google.maps.LatLng(<%=@current_latitude%>, <%=@current_longitude%>),
			destination: new google.maps.LatLng(<%=@location[0]%>, <%=@location[1]%>),
			travelMode: google.maps.TravelMode.WALKING

		};
		directionsService.route(request, function (response, status) {
			if (status === google.maps.DirectionsStatus.OK) {
				directionsDisplay.setDirections(response);
			}
		});
	});

</script>
<%end%>


<style>
	.rsvp-button {
		margin-right: 5px;
	}
	.btn-group {
		display: inline;
		margin-top: 20px;
	}
	form {
		display: inline;
	}

</style>