config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'sessions/new'
	get '/login/:user_id' => 'sessions#login_local' if Rails.env.development?
  get '/users/:id/creation_form' => 'users#creation_form'
  get '/users/auth/:provider/callback', to: 'sessions#create'
  resources :event_tags
  resources :interests
  resources :events
  resources :users, :except => :index
  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  get '/', to: 'events#home'
  get '/events/new', to: 'events#new'
  get '/events/new/trumba', to: 'events#new_trumba'
  get 'sponsor/:sponsor', to: 'events#filter_events'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search', to: 'events#search', as: 'search'
  get '/filter_events', to: 'events#filter_events', as: 'filter_events'
  post '/get_events', to: 'users#get_events', as: 'get_events'
  post '/change_privacy', to: 'users#change_privacy', as: 'change_privacy'
  get 'users/:id/new_account', to: 'users#creation_form', as: 'new_account'
  get '/top_events_json', to: 'events#top_events', :defaults => { :format => :json }
  get '/top_events_on_day/:date', to: 'events#top_events_on_day', :defaults => { :format => :json }


  get 'users/:calendar_hash/calendar-sync', to: 'users#to_icalendar'

  get '/events/:id/checkin', to: 'events#checkin'


  match '/404', :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  post '/rsvp', to: 'rsvps#rsvp', as: 'rsvp'
  post '/add_interest', to: 'interests#add_interest', as: 'add_interest'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#home'
end

app/views/layouts/_footer.html.erb
<footer class="copyright footer">
  <div class="container">
    <div class="col-md-6">
      <p>DISCLAIMER: Not endorsed by Brandeis University... yet. :)</p>
    </div>
    <div class="col-md-6">

      <ul class="bottom_ul" style="color:#fff;">

    <p><a href="https://docs.google.com/forms/d/e/1FAIpQLScjky6S1_2LoJqyL0fK9l2tivzZp-8tTdHqBR6VSX8W568b8Q/viewform?usp=sf_link" target="blank" style="color:#fff !important;">Submit Bugs</a>   /   Ari Carr   /  Aaron Gold   /   Zach Weiss</p>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section class="main-header text-center">
    <nav role="navigation" class="navbar navbar-default  navbar-fixed-top" id="nav">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <!-- Collection of nav links and other content for toggling -->
            <%#= link_to image_tag("Brandeis_seal_blue.svg.png", alt: "logo_scrolling", size: "60x60", id: 'logo_scrolling' ), '/', class: 'navbar-brand', id: 'navbar-brand-link'%>
            <%#= link_to "DeisToday", root_path, :class=>"navbar-brand", :id=>"logo_text" %>
            <%= link_to image_tag("DeistToday_Logo.png", alt: "logo", id: 'logo_blue' ), '/', class: 'navbar-brand', style:'padding-top:20px;'%>

            <%= link_to image_tag("DeistToday_Logo_White.png", alt: "logo", id: 'logo_white' ), '/', class: 'navbar-brand', style:'padding-top:20px;'%>

            <div id="navbarCollapse" class="collapse navbar-collapse">
                <!-- <%= link_to image_tag("Brandeis_seal_white.svg.png", alt: "logo", size: "60x60", id: 'logo' ), '/', class: 'navbar-brand'%> -->


                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "Browse Events", events_path %>
                    </li>

                    <li>
                        <%= (link_to "Add Event", events_new_trumba_path) if logged_in? %>
                    </li>
                    <% if can_host? %>
                    <!-- <li>
                        <%= link_to "Add Event", events_new_path %>
                    </li> -->
                    <% end %>
                    <% if is_admin? %>
                    <li>
                        <%= link_to "Admin", rails_admin_path %>
                    </li>
                <% else %>
                    <% end %>
                    <% if logged_in? %>
										<li>
                        <%= link_to "My Events", @current_user%>
                    </li>
                    <li>
                        <%= link_to "Settings", edit_user_path(@current_user)%>
                    </li>
                    <li>
                        <%= link_to "Sign out", logout_path %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Login", user_saml_omniauth_authorize_path %>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</section>

<script>
	//for automatic loading since block of next code is only for scrolling
	$(document).ready(function () {
		var logo_white = document.getElementById('logo_white');
		logo_white.style.display = 'none';
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <!-- <title>BrandeisEvents</title> -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-106402002-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments)};
          gtag('js', new Date());

          gtag('config', 'UA-106402002-1');
        </script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.js" integrity="" crossorigin="anonymous"></script>

        <!-- Google Maps -->

        <script src="//maps.google.com/maps/api/js?key=<%=ENV['Google_Maps_API']%>"></script>
        <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
        <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
        <!-- only if you need custom infoboxes -->
        <link rel="icon" href="https://www.brandeis.edu/communications/creative/downloads/4-inch-seal-pms-294.jpg">
        <title>DeisToday</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">

    </head>
    <%if @lat_lng.nil? %>

    <script>
        getGeoLocation();
    </script>
    <% end %>
    <%= render "layouts/header" %>
    <body>
        <%= yield %>
    </body>
    <%= render partial: '/layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

</html>